[build]
command = "hugo --gc --minify"
publish = "public"
base  = "website"

[build.environment]
HUGO_VERSION = "0.145.0"
NODE_VERSION = "23.10"

# must match the version in /website/go.mod
GO_VERSION = "1.24.1"
